## <center> Machine Learning from Scratch at ETH Zurich
## <center> 7. A Thorough Review of PyTorch
### <center> Zhaorui Gong &nbsp; 宫兆瑞

##  7.1 PyTorch数据处理
### 7.1.1 基本操作

In [79]:
import torch

In [78]:
x = torch.arange(15)
y = torch.arange(0, 15)
x, y

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]))

In [12]:
print(x.shape[0])
x.numel()

15


15

In [13]:
x = x.reshape(3, 5)
print(x)
y = x.reshape((1, 15))
print(y)
z = x.reshape(15)  
print(z)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])


In [4]:
w = z.reshape(5, -1)  # 固定行=5，列=-1表示自动算出
w

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [5]:
print(torch.zeros((2,3)))
torch.ones((2,3,4))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [6]:
torch.randn((2,3))  # standard normal distribution

tensor([[-0.0832,  0.3776,  0.4688],
        [ 0.0072,  1.4329, -0.4953]])

In [7]:
torch.tensor([[1.0, 2.0, 3.0], [3,4,5]])

tensor([[1., 2., 3.],
        [3., 4., 5.]])

### 7.1.2 运算符

In [8]:
x = torch.tensor([1,2,3,4])  # Elementwise
y = torch.tensor([2,2,2,2])
x + y, x - y, x * y, x / y, x ** y

(tensor([3, 4, 5, 6]),
 tensor([-1,  0,  1,  2]),
 tensor([2, 4, 6, 8]),
 tensor([0.5000, 1.0000, 1.5000, 2.0000]),
 tensor([ 1,  4,  9, 16]))

In [9]:
print(torch.exp(x))
torch.log(x)

tensor([ 2.7183,  7.3891, 20.0855, 54.5981])


tensor([0.0000, 0.6931, 1.0986, 1.3863])

In [14]:
x = torch.arange(12, dtype=torch.float32).reshape(3, 4)
y = torch.tensor([[2.0, 1, 4, 3], [1,2,3,4], [4,3,2,1]])
torch.cat((x, y), dim = 0), torch.cat((x, y), dim = 1)  # 行concatenation与列concatenation

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [15]:
x == y, x > y, x < y

(tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [20]:
print(x.sum(), x.sum(axis = 0))  # 全求和与对行求和
print(x.mean(axis = 1))   # 理解：axis = 0返回行向量， = 1返回列向量

tensor(66.) tensor([12., 15., 18., 21.])
tensor([1.5000, 5.5000, 9.5000])


### 7.1.3 广播机制 Broadcast Mechanism
当tensors形状不同时，我们仍可调用广播机制来执行elementwise operations

In [21]:
x = torch.arange(3).reshape((3, 1))
y = torch.arange(2).reshape((1, 2))
x, y

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [23]:
x + y  # x复制列，y复制行

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [37]:
x = torch.arange(3, dtype=torch.float32).reshape((1, 1, 3))
y = torch.arange(3, dtype=torch.float32).reshape((1, 3, 1))
z = torch.arange(2, dtype=torch.float32).reshape((2, 1, 1))
print(x, y, z)
x + y + z

tensor([[[0., 1., 2.]]]) tensor([[[0.],
         [1.],
         [2.]]]) tensor([[[0.]],

        [[1.]]])


tensor([[[0., 1., 2.],
         [1., 2., 3.],
         [2., 3., 4.]],

        [[1., 2., 3.],
         [2., 3., 4.],
         [3., 4., 5.]]])

### 7.1.4 索引和切片，与Python联系 Indexing and Slicing

In [31]:
x = torch.arange(12, dtype=torch.float32).reshape(3, 4)
x[-1], x[1:3]    # 注意二维数组是行向量拼在一起的，所以x[-1]是最后一行，x[1:3]是第2行和第3行组成的二维数组

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [32]:
x[0,1] = 100  # 写入
x[:, 2:4] = 200   # 所有行，第二与第三列
x

tensor([[  0., 100., 200., 200.],
        [  4.,   5., 200., 200.],
        [  8.,   9., 200., 200.]])

In [34]:
# 节省内存，复习指针
y = torch.arange(12, dtype=torch.float32).reshape(3, 4)
z = torch.zeros_like(y)
print(z.shape)
print('id(z):', id(z))
z[:] = x+y
print('id(z):', id(z))

torch.Size([3, 4])
id(z): 2501487011264
id(z): 2501487011264


In [38]:
# 转换为其他python对象
x = torch.tensor([3.5])
y = torch.tensor([1, 2])
print(x, y)
print(x, x.item(), float(x), int(x))
y.item, list(y), y.tolist()

tensor([3.5000]) tensor([1, 2])
tensor([3.5000]) 3.5 3.5 3


(<function Tensor.item>, [tensor(1), tensor(2)], [1, 2])

## 7.2 PyTorch与线性代数
### 7.2.1 矩阵与张量


In [40]:
A = torch.arange(20).reshape(5, 4)
print(A == A.T.T)
A, A.T

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  4,  8, 12, 16],
         [ 1,  5,  9, 13, 17],
         [ 2,  6, 10, 14, 18],
         [ 3,  7, 11, 15, 19]]))

In [48]:
# 张量是矩阵的推广。矩阵是二阶张量，向量是一阶张量，标量是零阶张量。
# 3-order tensor用于处理彩色图像，4-order tensor用于存储视频等。
X = torch.arange(25, 49).reshape(1, 2, 3, 4)
X

tensor([[[[25, 26, 27, 28],
          [29, 30, 31, 32],
          [33, 34, 35, 36]],

         [[37, 38, 39, 40],
          [41, 42, 43, 44],
          [45, 46, 47, 48]]]])

### 7.2.2 张量运算的基本性质

In [51]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()
A + B, A * B, A / B  # elementwise, Hadamard operation

(tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]),
 tensor([[nan, 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [52]:
a = 1
A + a   # 张量+标量不会改变形状。根据广播机制，标量a会被自动扩展成与A形状相同的张量，然后进行逐元素运算

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.],
        [17., 18., 19., 20.]])

In [56]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis1 = A.sum(axis=1)
print(A_sum_axis0, A_sum_axis0.shape)
print(A_sum_axis1, A_sum_axis1.shape)
A.mean(axis=0), A.sum(axis=0) / A.shape[0] # mean与sum的关系，通过降维来理解

tensor([40., 45., 50., 55.]) torch.Size([4])
tensor([ 6., 22., 38., 54., 70.]) torch.Size([5])


(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [61]:
# 非降维求和：参数保持维度
sum_A = A.sum(axis = 1, keepdims=True)
print(sum_A, sum_A.shape)
# 非降维求和：累计求和
print(A.cumsum(axis=0), A.cumsum(axis=1), A.cumsum(axis=1).shape)    

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]]) torch.Size([5, 1])


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.],
         [24., 28., 32., 36.],
         [40., 45., 50., 55.]]),
 tensor([[ 0.,  1.,  3.,  6.],
         [ 4.,  9., 15., 22.],
         [ 8., 17., 27., 38.],
         [12., 25., 39., 54.],
         [16., 33., 51., 70.]]),
 torch.Size([5, 4]))

### 7.2.3 点乘与矩阵乘法

In [70]:
x = torch.arange(4, dtype=torch.float32)  # 这里必须改type，否则是long，无法用dot点乘
y = torch.ones(4)   # ones的type自动是float32
print(x, y)
print(torch.dot(x, y))
print(torch.sum(x * y)) # 点乘的定义：对应元素相乘后求和

tensor([0., 1., 2., 3.]) tensor([1., 1., 1., 1.])
tensor(6.)
tensor(6.)


In [73]:

# 矩阵-向量内积
print(A.shape, x.shape)
torch.mv(A, x)  # 此处不能用dot()，它只接受两个1D tensors

torch.Size([5, 4]) torch.Size([4])


tensor([ 14.,  38.,  62.,  86., 110.])

In [74]:
B = torch.ones(4, 2)
torch.mm(A, B)  # 矩阵乘法

tensor([[ 6.,  6.],
        [22., 22.],
        [38., 38.],
        [54., 54.],
        [70., 70.]])

In [77]:
# 范数
u = torch.tensor([3.0, -4.0])
print("L2-norm:", torch.norm(u))  # 默认是L2-norm，即欧几里得范数
print("L1-norm:", torch.abs(u).sum())
u = torch.ones((4, 9))   # 4 by 9 matrix
print("Frobenius norm:", torch.norm(u))  # 矩阵的Frobenius范数，即所有元素的平方和的平方根


L2-norm: tensor(5.)
L1-norm: tensor(7.)
Frobenius norm: tensor(6.)


## 7.3 PyTorch自动微分
### 7.3.1 反向传播：标量与非标量output

In [99]:
x = torch.arange(4.0, requires_grad  = True)
x, x.grad  # 默认是None

(tensor([0., 1., 2., 3.], requires_grad=True), None)

In [100]:
# 以y = 2x^T x为例
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [101]:
y.backward()
x.grad   # dy/dx = 4x

tensor([ 0.,  4.,  8., 12.])

In [102]:
x.grad == 4*x  # 手动检验

tensor([True, True, True, True])

In [103]:
# 默认torch会累积梯度值，所以在计算其他f(x)对x的梯度前，要先清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [104]:
# 非标量变量的反向传播
x.grad.zero_()
y = x*x
y.sum().backward()
# y.backward() 注意直接这样写会报错，因为y是一个向量，无法直接进行反向传播,因为不知道你的优化目标是什么，需要先求和得到标量
x.grad, x

(tensor([0., 2., 4., 6.]), tensor([0., 1., 2., 3.], requires_grad=True))

In [105]:
# 或者对向量调用backward需要传入一个gradient参数，该参数指定微分函数关于self的梯度。这个方法更通用。
x.grad.zero_()
y = x*x  # 需要再定义一遍，否则上面y.backward()会报错，因为y已经被求和了，不是之前的那个向量了。
y.backward(torch.ones_like(x))  # ∂(y·v)/∂x = ∂(y₁v₁ + y₂v₂ + ... + yₙvₙ)/∂x, where v = torch.ones_like(x)
x.grad, x                       # i.e. y·v = y₁ + y₂ + ... + yₙ = sum(y)，因此二者等价。

(tensor([0., 2., 4., 6.]), tensor([0., 1., 2., 3.], requires_grad=True))

In [106]:
# 另一个例子
x = torch.tensor([2.0, 3.0], requires_grad=True)
y = x * x

# 假设我们只关心第一个输出
v = torch.tensor([1.0, 0])
y.backward(v)
print(x.grad)  # 输出: [4.0, 0.0] 因为只对第一个输出求导

# 假设我们想给不同输出不同权重
x.grad.zero_()
y = x * x
v = torch.tensor([0.5, 2])
y.backward(v)
print(x.grad)  # 输出: [2.0, 12.0] (因为 0.5*2x₁ 和 2.0*2x₂)

tensor([4., 0.])
tensor([ 2., 12.])


### 7.3.2 分离计算

In [112]:
# 希望将某些计算移动到computation graph之外，来节省内存。e.g. x -> y, x, y -> z, 希望将y视作一个常数
x = torch.arange(4, requires_grad=True, dtype=torch.float32)
y = x*x
u = y.detach()  # detach()会返回一个新的tensor，它与原tensor共享数据，但不再是计算图的一部分
z = u*x
v = torch.ones_like(z)
z.backward(v)
x.grad, x.grad == u

(tensor([0., 1., 4., 9.]), tensor([True, True, True, True]))

In [113]:
# 随后我们可以在y上调用反向传播，得到y对x的梯度
x.grad.zero_()
y.backward(v)
x.grad, x.grad == 2*x

(tensor([0., 2., 4., 6.]), tensor([True, True, True, True]))

### 7.3.3 Python控制流下的梯度计算
自动微分的好处包括，即使构建函数的计算图需要通过控制流，如条件、循环和其他函数调用，也不影响自动微分

In [132]:
def f(x):
    y = x * 2
    while y.norm() < 1000:
        y *= 2
    if y.sum() > 0:
        z = y
    else:
        z = 100 * y
    return z

a = torch.randn(size=((3,1)), requires_grad=True)
b = f(a)   # 注意f(a)对a是分段线性的，即对任意a，都存在k s.t. b = k*a, 因此b.backward()不会报错
v = torch.ones_like(b)
b.backward(v)
a.grad, a.grad == torch.abs(b/a)


(tensor([[102400.],
         [102400.],
         [102400.]]),
 tensor([[True],
         [True],
         [True]]))

## 7.4 矢量化加速
在模型训练时，当训练数据集n很大，我们经常希望同时处理小批量的样本，因此应进行矢量化从而利用线性代数库，而不是对每个数据点进行算力高昂的for循环。

In [134]:
%matplotlib inline
import math
import time
import numpy as np
import torch
from d2l import torch as d2l

In [ ]:
n = 10000  # 10000-dim vector
a, b = torch.ones(n), torch.ones(n)

class Timer: #@save
    '''记录多次运行时间，进行时间基准测试'''
    def __init__(self):
        self.times = []
        self.tik = None
        self.start() # 自动启动

    def start(self):
        '''启动计时器'''
        self.tik = time.time()
    
    def stop(self):
        '''停止计时器并将时间记录在列表中'''
        self.times.append(time.time() - self.tik)
        return self.times[-1]

    def avg(self):
        return sum(self.times) / len(self.times)

    def sum(self):
        return sum(self.times)

    def cumsum(self):
        return torch.tensor(self.times).cumsum().tolist()

In [141]:
# 用for循环执行每一位加法
c = torch.zeros(n)
timer = Timer()
for i in range(n):
    c[i] = a[i] + b[i]
print(f'{timer.stop():.6f} sec')

0.082363 sec


In [143]:
timer.start()
d = a+b
print(f'{timer.stop():.6f} sec')
# 可见，矢量/tensor化可带来数量级的运算加速。

0.000000 sec
